package com.cgvsu.objwriter;

import com.cgvsu.math.Vector2f;
import com.cgvsu.math.Vector3f;
import com.cgvsu.model.Model;
import com.cgvsu.model.Polygon;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

public class ObjWriter {
    public static void write(Model model, String filename) throws IOException {
        try (FileWriter writer = new FileWriter(filename)) {
            writer.write("# Generated by 3D Model Viewer\n");
            writer.write("# Vertices: " + model.vertices.size() + "\n");
            writer.write("# Polygons: " + model.polygons.size() + "\n\n");

            for (Vector3f vertex : model.vertices) {
                writer.write(String.format("v %.6f %.6f %.6f\n",
                        vertex.x, vertex.y, vertex.z));
            }

            if (!model.textureVertices.isEmpty()) {
                writer.write("\n");
                for (Vector2f textureVertex : model.textureVertices) {
                    writer.write(String.format("vt %.6f %.6f\n",
                            textureVertex.x, textureVertex.y));
                }
            }

            if (!model.normals.isEmpty()) {
                writer.write("\n");
                for (Vector3f normal : model.normals) {
                    writer.write(String.format("vn %.6f %.6f %.6f\n",
                            normal.x, normal.y, normal.z));
                }
            }

            writer.write("\n");
            for (Polygon polygon : model.polygons) {
                writer.write("f");

                List<Integer> vertexIndices = polygon.getVertexIndices();
                List<Integer> textureIndices = polygon.getTextureVertexIndices();
                List<Integer> normalIndices = polygon.getNormalIndices();

                for (int i = 0; i < vertexIndices.size(); i++) {
                    writer.write(" ");

                    int vIdx = vertexIndices.get(i) + 1; // OBJ индексы с 1

                    if (!textureIndices.isEmpty() && !normalIndices.isEmpty()) {
                        int vtIdx = textureIndices.get(i) + 1;
                        int vnIdx = normalIndices.get(i) + 1;
                        writer.write(vIdx + "/" + vtIdx + "/" + vnIdx);
                    } else if (!textureIndices.isEmpty()) {
                        int vtIdx = textureIndices.get(i) + 1;
                        writer.write(vIdx + "/" + vtIdx);
                    } else if (!normalIndices.isEmpty()) {
                        int vnIdx = normalIndices.get(i) + 1;
                        writer.write(vIdx + "//" + vnIdx);
                    } else {
                        writer.write(String.valueOf(vIdx));
                    }
                }
                writer.write("\n");
            }
        }
    }
}